### ISSUE TITLE
Do `yarn migrate` is need for first install after uwazi v1.4?

### ISSUE THREAD

**Issue by fititnt** [fititnt/uwazi-docker#41]
Pertinent change https://github.com/huridocs/uwazi/commit/fcfc25e95f98191df4cf364e03ebd3ed719a7ba2

The v1.4 now runs `yarn migrate` after `./database/blank_state.sh` and before `yarn reindex`.

If this is one yes, a new change will need to be done at the https://github.com/fititnt/uwazi-docker/blob/master/docker-entrypoint.sh. This issue is just to confirm the need.

Edit: also impacts the https://github.com/fititnt/uwazi-docker/issues/40

**Comment by txau** [comment]
@fititnt in principle the blank state comes already with the latest data structure so there is not need to run 'yarn migrate'. That said, its always safe to run migrate since it keeps track of the data version and won't alter anything if its already up to date.

So its safer to run it, in case a dev forgets to update the blank state after a breaking change, but the odds of that are super low.

**Comment by fititnt** [comment]
Ah ok ok. It's not super critical, but will do it later.

**Comment by fititnt** [comment]
Documented this strategy to do it on dockerized version. It is necessary because the normal run up we do not automate         yarn migrate / yarn reindex, and in some cases (no major MongoDB/ElasticSearch database upgrade) this migth be sufficient.

```bash
docker compose run -e RUN_YARN_MIGRATE_REINDEX=true --rm uwazi
```
